// Code generated by "esc -o queries.go -pkg postgres -private ./queries.sql"; DO NOT EDIT.

package postgres

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/queries.sql": {
		name:    "queries.sql",
		local:   "./queries.sql",
		size:    5780,
		modtime: 1582676133,
		compressed: `
H4sIAAAAAAAC/+zX32+bPhAA8OfcX3EP/qqp5H412v3eeKCJo6ES6MBZm70gGjzVWko6IF0r9Y+fDGmA
AKu0SFsi8VKp+Gyf7+NLwtERRsGNeI+zWASp8JeJiBM/Da7mAgYuMzhDbpxaDM0R2g5Hdml63MMsDPvQ
kyFydsnx3DXHhjvFMzal0MsXC/0gRW6OmceN8Tn/mi1gTyyLQm95Gz4TEcxSedcQQ6EnbgI5z/ctLxnd
iVh+kyL0iwAKvdsgSX4u4tC/DpJrPJ1yZpSn5ZNmQSoXkZ8uvouoFLg5Hon7tJ5PJUTc38pYJPWoWMwW
dyJ+aNpkPda8wXq4dfGBY3vcNUybY3Z4fxnJH0uBE9v8PGH97NkhHH4AWIvLKBFxmomDaXvM5Wja3FnZ
fjGsCfOwTzSK5JgiOaFIXlIkryiS1xTJG4rkLUXyjiLRXqg/KlJTodpJZaPcOtvIv3rwZQiT86G6WflO
HuNYug46Eo1CRV/PMoBcVVepQA1bV9lB1VpX2UIbsK7OAY28ujoetLHq6uDQxKmrckANU88qBE2KakjD
i0/MZSjD7N/jcu1CMRfV2g2ZxTjDkeuMVwWszG6YLKOsmqvmbl1go+SqPdCwh9hWho9oOxf9inQi5mKW
lrP1mMUGHGVIEYpPBQoFeNWa5sp14A3bdlbDq2T8f0P0k8tm6Op5u/zmhGKo+T4YHj49XuVRuxvlkPX+
TTelHFg8hrZ7gJY5Njlqv+HJ6toJ/XWh9QfWc0jJWskPRTLzC55O7R+pWeYZU3CPj3jw3wE67pC5eDrF
0i+eIfMGK1hyjM5opL7gyMnzxkFHvCfExh8KZ11c+HXEO0Zc+hm6VRd3xPtAvFUXl8065B1DrrzKbNXJ
HfO+MG/Vzd2r0C765qNb9W8Hu7uwbR37KwAA//8cWxj4lBYAAA==
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
