// Code generated by "esc -o queries.go -pkg postgres -private ./queries.sql"; DO NOT EDIT.

package postgres

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/queries.sql": {
		name:    "queries.sql",
		local:   "./queries.sql",
		size:    6023,
		modtime: 1583514726,
		compressed: `
H4sIAAAAAAAC/+yX32+bOhTHn+O/4ijiqsmVe3Vp97vjgSaOhkqgA2dt9oIoeCpaSjpwulbKHz/ZpMEU
WKXlYY3ESyQ4X/scn8/3EDg8hDS8YR8gyljIWbDKWZYHPLxaMDTyiEkJUPPUJmBNwHEpkEvLpz5IGQxQ
L4mBkksK5541Nb05nJE5Rr1iszgIOVBrSnxqTs/pV7mBM7NtjHqr2/gZRRjx5K5Bg1GP3YTJosirbpne
sSz5lrA4KAUY9W7DPP+5zOLgOsyv4XROiakuKxZFIU+WacCX31mqCJ/GU3bP6/VUJOz+NslYXldlLFre
seyhKck21pxgG27dfOQ6PvVMy6EgDx+s0uTHisHMsT7PyEDeG6LhCUJoizxnCxbxIOchz5FPbDKiMHJn
Dh38OwTTB77k4SKIlquUw8RzpwX1E2WHJM1ZxqVpkOX4xKNgOdTd2OOLac+IDwNNx6AdYdCOMWivMGiv
MWhvMGhvMWjvMGjvMWj6/+JHKHUh1Y+HaqLCLjJRcPUQJDGanY+FOYtMPqGgOMoATceoYiBDVoAKYxii
FFTziyGqQ1W7GKJa1OYRQ5wDNTrEEMdDbc4wxMFRkyMM0Q5U84MhO4SajCBCOlx8Ih6BJJaXR2rvYrZg
1d6NiU0oUZhWVzcsTlLZzc3zoXWDJy0XEwamM4a2NnwEx70YVEhvTKlUu3FmEmNA5YMFoxJ4lTUuKNcB
P2HbjtX0oa/G/hN3+y2ga+JNoN9Ov7akjPWbXSFWPN5/rKbmkYqorKLJMxWpkh21eQJsa2pR0H+DSva4
o/VXaW0fZM8By7fEgpjlUVCi6gi+AIK2dUbg4J8DWK8Fy/VaXrjemHhwOgfl/WpM/NGGtXYE7mQi/gu1
4+exhx31/aVu/iF0Oesl0o76y6euvNfuNOsd9T2lvtOsqxg77i+fe+ULaqd578jvMfmdZr77ENsT5IVo
pynvWO8V67a5/hUAAP//UDgZ3YcXAAA=
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
