// Code generated by "esc -o queries.go -pkg postgres -private ./queries.sql"; DO NOT EDIT.

package postgres

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/queries.sql": {
		name:    "queries.sql",
		local:   "./queries.sql",
		size:    1960,
		modtime: 1581546805,
		compressed: `
H4sIAAAAAAAC/+yUS3ObMBDHz95PsQcdnBmlU5K+Ww4kVqZMMXZBbuJeGALqRFMbu4Dd5Nt3JFxAPCbH
XnrxjLX/fej/W3R+jlm8FR8wyUVciuhQiLyIyvh+I+A6YA5nyJ0rj6F7g/6CI7tzQx6iluEUJjJFzu44
LgN37gRr/MLWFCZVsTSKS+TunIXcmS/5d13AX3kehclhnz6jiJNSHgc0FCZiG8tN1bddMjuKXP6QIo0a
AYXJPi6K37s8jR7i4gGv1pw57bQqKYlLucuicvdTZC1hN56Jx7I/jyERj3uZi6KvykWyO4r8aahJHRtu
UIdHi18v/JAHjutz1JePDpn8dRC48t2vKzbVZ2dw9hGgJi6zQuSlJg6uH7KAo+vzxYntN8dbsRCnxKJI
LiiSS4rkFUXymiJ5Q5G8pUjeUSTvKRLrpfpRSktJrUujUcVaN4runyKZwmo5U5tVdQoZx9Y62EgsCgZ9
W08AFVVbjQI92LaaDkzWtpoWxgDb6h4wiNdW14MxrLa6OAzhtJUd0INpa4dgiKIKWXj7mQUMZar/XrS9
S8VGmN7NmMc4w5tgMT8ZaGQPJMtMu3n6uEcLdCxXnwc6/gzHbPiE/uJ2apAuxEYkZZQcinK3rScOmceu
OcqUIjQvA4UGusmbVqT7kDt8x9E6oTH1iyY0ArybcDof34FuQhMa3gwnxL/HxjS9XWkL6ymGNqctbI5h
bC/Qc+cuR+sZXNrn/8T+KbH6QWtB+xMAAP//5t1T5agHAAA=
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
